### PR TITLE
Added support for annotations, renamed env vars, added login auth, added content-type html

### LINKED ISSUE #16: Needs support for annotations
This handler should include support for annotations similar to the Slack handler, at least for items like the Subject and Body templates.  This could also serve as an alternative to the template file that was added prior.

### LINKED ISSUE #18: Error: failed to send email: 504 5.7.4 Unrecognized authentication type
Hi,
I'm trying to send emails using `smtp.office365.com` but I get this error:

`Error: failed to send email: 504 5.7.4 Unrecognized authentication type [DBBPR09CA0015.eurprd09.prod.outlook.com]`

I'm using the same credential/settings successfully used by other applications (e.g. grafana).

Thanks

### LINKED ISSUE #20: Is it able to parse a html or erb templates?
Hi Team,

I have template as mentioned below
Sensu Alert - {{.Entity.Name}}

I am able to parse above template and I have received email

Is this script able to parse html or erb template as mentioned below
<html>
<head>
</style>
</head>
<body>
        <tr >
                <td>Check Name: </td>
                <td> {{.Check.Name}}
                </td>
        </tr>
</body>
</html>

As I checked, I am not able to parse it 
How Can I present the mail in a tabular format

### PR DESCRIPTION
**Pull request by nixwiz**
Closes #16 
Closes #18 
Closes #20 

The environment variables change is a breaking change, but was done to maintain consistency for variable naming.

Signed-off-by: Todd Campbell <todd@toddcampbell.net>

### CODE REVIEW

**Comment by aphix** [comment]
Was just looking to figure out how to enable login auth and found this. I would love for this PR to be merged, rather than building/running a fork on a new monitoring environment.

**Comment by nixwiz** [comment]
@nikkiki any reason why the other pull request was prioritized over this one and now has conflicts for me to resolve?

**Comment by nikkiki** [comment]
Hey @nixwiz I'm really sorry about the merge conflicts that were created as a result of the last merge. We really dropped the ball here on keeping high visibility over this repo. I've queued up some discussion with the team to improve our processes with supported plugins, and to ensure that it doesn't happen again. Since this issue in particular seemed to fly under the radar, I can make sure to look at it as soon as the conflicts are resolved. Thank you so much for your contributions, we'll try and make this better!

**Comment by nixwiz** [comment]
@nikkiki given how much of an overhaul that other PR was, I'm going to close this and attempt to re-address these issues separately.

**Pull request closed without merging**
